[package]
name = "watch"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "1.1.1"
nanoserde = "0.1.30"

[profile.release]
panic = "abort"
lto = true
strip = true
