[package]
name = "watch"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "1.1.1"
serde = "1.0.147"
serde_derive = "1.0.147"
serde_json = "1.0.87"
